[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name="tetris"
path="src/tetris.rs"

[dependencies]
ggez = "0.7"
oorandom = "11.1.3"
getrandom = "0.2.5"
mint = "0.5.6"
